name: (Dev) Build LineageOS

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Set up JDK
      uses: actions/setup-java@main
      with:
        java-version: '21'

    - name: Initialization environment
      id: init
      env:
        DEBIAN_FRONTEND: noninteractive
      working-directory: /
      run: |
        echo -e "Current working directory: $(pwd)"

        packages_install=(
            "bc" 
            "bison" 
            "build-essential" 
            "ccache" 
            "curl" 
            "flex"
            "g++-multilib" 
            "gcc-multilib" 
            "git" 
            "git-lfs" 
            "gnupg"
            "gperf" 
            "imagemagick" 
            "lib32readline-dev" 
            "lib32z1-dev"
            "libelf-dev" 
            "liblz4-tool" 
            "libsdl1.2-dev" 
            "libssl-dev"
            "libxml2" 
            "libxml2-utils" 
            "lzop" 
            "pngcrush" 
            "rsync"
            "schedtool" 
            "squashfs-tools" 
            "xsltproc" 
            "zip" 
            "zlib1g-dev"
        )

        sudo -E apt-get -qq -y update
        sudo -E apt-get -qq -y install "${packages_install[@]}"
        sudo -E systemctl daemon-reload

        echo "status=success" >> ${GITHUB_OUTPUT}

    - name: Set up ccache
      id: ccache
      if: ${{ 'true' == 'false' }} # disable
      working-directory: /
      run: |
        export USE_CCACHE=1
        export CCACHE_EXEC=/usr/bin/ccache
        ccache -M 50G

    - name: Initialize LineageOS source
      working-directory: /
      run: |
        mkdir -p ~/android/lineage
        cd ~/android/lineage
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        ~/bin/repo init -u https://github.com/LineageOS/android.git -b lineage-18.1 --git-lfs

    - name: Sync LineageOS source
      run: |
        cd ~/android/lineage
        repo sync -j4

    - name: Build LineageOS
      run: |
        source build/envsetup.sh
        breakfast ginkgo
        croot
        brunch ginkgo

    - name: Upload OpenWrt to Release
      id: release
      uses: ncipollo/release-action@main
      with:
        name: "lineageos-build"
        tag: "lineageos"
        artifacts: "~/android/lineage/out/target/product/ginkgo/*.zip"
        allowUpdates: true
        removeArtifacts: false
        replacesArtifacts: true
        token: "${{ secrets.GITHUB_TOKEN }}"
        # bodyFile: "${{ env.release_md }}"
        body: "lineageos"
        
