name: Call Build

# https://docs.github.com/zh/actions/writing-workflows/workflow-syntax-for-github-actions
run-name: Build Matrix for AOSP

on:
  # schedule:
  #   # Run every day at 20:00 UTC
  #   - cron: "0 20 * * *"
  repository_dispatch:
  workflow_dispatch:

jobs:
  uboot:
    name: ${{ matrix.workflows_inputs.device_code }}
    uses: ./.github/workflows/lineageos-dev.yml
    strategy:
      fail-fast: false
      matrix:
        runner_image: ["ubuntu-24.04"]
        workflows_inputs:
          # https://wiki.lineageos.org/emulator
          # ========== Phone ==========
          - manifest-repo: "https://github.com/LineageOS/android.git"
            manifest-branch: "lineage-17.1"
            device_code: "ginkgo"
            lunch_code: "lineage_arm-userdebug"
          - manifest-repo: "https://github.com/LineageOS/android.git"
            manifest-branch: "lineage-18.1"
            device_code: "flame"
            lunch_code: "lineage_arm-userdebug"
          # ========== x86_64 ==========
          # ---------- lineage-17.1 ----------
          - manifest-repo: "https://github.com/LineageOS/android.git"
            manifest-branch: "lineage-17.1"
            device_code: "x86_64"
            lunch_code: "lineage_x86_64-userdebug"
          - manifest-repo: "https://github.com/LineageOS/android.git"
            manifest-branch: "lineage-17.1"
            device_code: "x86_64"
            lunch_code: "aosp_x86_64-eng"
          # ---------- lineage-14.1 ----------
          - manifest-repo: "https://github.com/LineageOS/android.git"
            manifest-branch: "cm-14.1"
            device_code: "x86_64"
            lunch_code: "aosp_x86_64-eng"
          # ---------- lineage-11.0 ----------
          - manifest-repo: "https://github.com/LineageOS/android.git"
            manifest-branch: "cm-11.0"
            device_code: "aosp_x86-eng"
    with:
      runner_image: ${{ matrix.runner_image }}
      manifest-repo: ${{ matrix.workflows_inputs.manifest-repo }}
      manifest-branch: ${{ matrix.workflows_inputs.manifest-branch }}
      device_code: ${{ matrix.workflows_inputs.device_code }}
      lunch_code: ${{ matrix.workflows_inputs.lunch_code }}
      breakfast_code: ${{ matrix.workflows_inputs.device_code || '' }}
      brunch_code: ${{ matrix.workflows_inputs.device_code || '' }}
